# Generated by Django 4.2.7 on 2023-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
