# Generated by Django 4.2.7 on 2023-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_students_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='enroll_number',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
