# Generated by Django 4.2.7 on 2023-11-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='media/faces'),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
